### PR TITLE
Add data model 2

### PR DESCRIPTION
**Pull request by snsmith92**
@ilyakrasnov  and @drewsef-916  -- I compared and resolved the conflicts between master and add_data_model and made a new branch (this branch ;). Seems there are no longer conflicts. Can you approve @ilyakrasnov ?

### CODE REVIEW

**Comment by ilyakrasnov** [comment]
👍

**Comment by snsmith92** [comment]
I had some trouble with the migrations to remove the white_player and black_player columns from the games table @ilyakrasnov @drewsef-916 . We still need to get this working I think before merging with master or....?

**Comment by snsmith92** [comment]
I think it's fixed! @ilyakrasnov @drewsef-916 what do you think?

**Comment by ilyakrasnov** [comment]
Looks good @snsmith92 👍

**Pull request merged**
